ROOT_PATH = ''
CONFIG_PATH = ROOT_PATH + 'config.json'
DATASET_DIRECTORY_PATH = ROOT_PATH + 'dataset/'
DATA_PATH = DATASET_DIRECTORY_PATH + 'emotion.data'
USE_CUDA = True
ENABLE_LOGGING = True
DEVICE = 'cpu'